batch_size: 128 # 128
num_epochs: 10
lr: 0.0008 # 0.0008
weight_decay: 0.0005
label_smoothing_epsilon: 0.3 # 0.3
init_emb_size: 1024 # 256 # 32
gc1_emb_size: 512 # 128 # 48
embedding_dim: 256 # 32 # 32
input_dropout: 0.08 # 0.08
dropout_rate: 0.24 # 0.24
channels: 100 # 10
kernel_size: 3 # 3
n_clusters: 3
label_relation: has_label
patience: 100