batch_size: 128
num_epochs: 3
lr: 0.01
weight_decay: 0.001
label_smoothing_epsilon: 0.2
init_emb_size: 128  # 64
gc1_emb_size: 64  # 32
embedding_dim: 16  # 16
input_dropout: 0.25
dropout_rate: 0.00  # 0.25
channels: 200
kernel_size: 3
n_clusters: 3
label_relation: has_label
patience: 100