batch_size: 128
num_epochs: 50
lr: 0.005 # 0.01
weight_decay: 0.001 # 0.001
label_smoothing_epsilon: 0.0
init_emb_size: 1024 # 32
gc1_emb_size: 512 # 48
embedding_dim: 256 # 32
input_dropout: 0.00
dropout_rate: 0.0 # 0.25
channels: 170 # 40
kernel_size: 3
n_clusters: 3
label_relation: has_label
patience: 100